### ISSUE TITLE
"Cannot read property 'password' of undefined"

### ISSUE THREAD

**Issue by jasondbchapman** [strongloop/loopback-connector-cloudant#100]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

After updating to the latest Angular CLI I have been receiving this error everytime that I attempt to send a post or get request to upload/retrieve a document.  

I am not clear what property password it is referring to and why this error is occurring after I updated the angular cli.  

### Expected result

I am hoping to be able to upload and retrieve documents from my cloudant db

### Actual result (if bug)

I receive the following error: 

"error": {
    "name": "TypeError",
    "status": 500,
    "message": "Cannot read property 'password' of undefined",
    "stack": "TypeError: Cannot read property 'password' of undefined\n
}

### Additional information (Node.js version, LoopBack version, etc)

Noje.js version = 7.7.3
LoopBack version = 2.38.2

**Comment by jasondbchapman** [comment]
Wanted to follow up and see if anyone had any ideas on how to fix this issue? I have not yet found a workaround

**Comment by b-admike** [comment]
hi @jasondbchapman, thank you for your detailed description of the issue. Can you provide high level steps you took before you hit the issue and the full stack trace of the error? Anything else you think can be helpful as well.

**Comment by kjdelisle** [comment]
This issue sounds like it's potentially related to the Angular component, and not necessarily this connector. Do you have any reproduction you can provide that demonstrates this working up until the connector layer? If we can see that the "password" value is making its way down to the connector level before erroring out, then this issue would make sense.

Otherwise, I'd like to close this and would encourage you to open a ticket against https://github.com/strongloop/loopback-sdk-angular-cli or https://github.com/strongloop/loopback-sdk-angular
