### ISSUE TITLE
Loopback-cloudant-connector creates a _all_fields  index in cloudant by default

### ISSUE THREAD

**Issue by akshaysin** [strongloop/loopback-connector-cloudant#162]
### Bug or feature request

- Bug

### Description of feature (or steps to reproduce if bug)

Sometime back it was noticed that loopback by default created indexes on all_feilds(on any db in cloudant) if you use loopback-cloudant-adapter. However Cloudant support strongly discourages that practice. We are in fact having a lot of performance issues with Cloudant lately and this was one of the recommendation by Cloudant support. So we were trying to figure out a way to make loopback-cloudant-connector not create index on all_feilds and only create it on the ones that we actually need. In words of one of our developers :

_We are trying to modify the existing all-field index to specific properties in cloudant models
To accomplish this we tried  modifying the existing design documents in cloudant and added specific index fields  and tried to invoke the  loopback services. The basic crud opertions failed with error Error: mango_idx :: {no_usable_index,missing_sort_index} and also upon app restart the cloudant design document was overwritten to  index on all fields.
We want support on modifying existing design documents to index on specific properties and also disable the default loopback functionality to create cloudant indexes on all_feilds_

### Expected result

loopback-cloudant-Connector dosen't creates a all_feilds index on the underlying databases

### Actual result (if bug)

loopback-cloudant-Connector creates a all_feilds index on the underlying databases

### Additional information (Node.js version, LoopBack version, etc)

Loopback version : 3.6.0
Node js Version : 6.10

**Comment by djorg83** [comment]
+1

**Comment by jannyHou** [comment]
Hi @akshaysin @djorg83 If you remove the all_fields index for the sake of performance, you could not do ad-hoc sort without creating index for the property anymore, otherwise you see the error above 
> Error: mango_idx :: {no_usable_index,missing_sort_index} 

all_fields index implies two things:
- 1. supports ad-hoc selector even you don't create index for the property in `selector` object
- 2. supports ad-hoc sort even you don't create index for the property in `sort` object

By specifying the indexable fields, you will probably still be able to do 1, since cloudant has some index matching algorithm to guarantee if no custom index to use, it then uses all_fields index, but **you lose the ability to do 2**.

I agree that the performance needs enhancement, AFAIK we can allow user to customize indexable fields, while just you have to be aware of the consequent sorting problem.

**Comment by ritch** [comment]
Just to clarify @jannyHou - with the existing version of the cloudant connector, can I disable the `all_fields` index?

If so, a workaround for now would be to just disable the `all_fields` index and add in indexes for all properties you would like to query / sort (pretty common requirement for something like this).

If you can't disable the index, we should add a new issue to track that.

/cc @kjdelisle

**Comment by jannyHou** [comment]
@ritch User need to hack the code to disable `all_fields` index, this is hard-coded in our connector.

**Comment by willholley** [comment]
@jannyHou in recent versions of Cloudant (Cloudant Local 1.1 or Cloudant aaS) you should never see the `no_usable_index,missing_sort_index` error - if you do, it's a bug in Cloudant. Indexes should only impact performance - they should not change the result/response to a query.

**Comment by kjdelisle** [comment]
@akshaysin This is now fixed as of Cloudant 2.0.2, which has been released!
