### ISSUE TITLE
Use built in _id field and index

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-connector-cloudant#165]
Looks like we are not making it possible to use the built in `_id` field and index and instead create a separate index and alias. We should support disabling this separate index.

**Comment by kjdelisle** [comment]
This issue is being raised as a performance issue, but whoever ends up taking this task should run a performance test with two different versions of the same model:
- One where the id is autogenerated (`id`)
- One where you explicitly declare `_id` as a field, and mark it with `{ id: true }`

If this doesn't yield a statistically significant difference in performance, then we'll need to re-evaluate the importance of this issue.

**Comment by kjdelisle** [comment]
So, I've run some automated tests with both these scenarios against the LoopBack Notes template, on Cloudant Local and found no statistically significant difference in performance between them. I'm not sure where the performance complaint stems from in that respect.

I think as a workaround, users can explicitly define `_id` as a field on their models for the loopback-connector-cloudant in the 1.x release. There's a bug with this version that currently removes the `_id` field if present, which will break this approach, but we have a PR to address this: https://github.com/strongloop/loopback-connector-cloudant/pull/170

**Comment by kjdelisle** [comment]
The greater problem stems from the idea that LoopBack 3 itself is the reason for the default `id` alias, which is not something that can be controlled for at this level.

**Comment by kjdelisle** [comment]
Fixed and released!
