### ISSUE TITLE
findById optimization

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-connector-cloudant#166]
We should use the built in `get` function when retrieving by _id (`findById()`) to allow for driver / db optimizations. If this is only possible in certain cases (eg. only using the default `_id` index, we should allow for this under that use case / configuration).

**Comment by jannyHou** [comment]
- “The Cloudant connector uses `find` instead of `get` for `findById` queries.”
This is not true, actually loopback-connector-cloudant@1.x is using api `get` to fetch the instance, please check code in https://github.com/strongloop/loopback-connector-cloudant/blob/1.x/lib/cloudant.js#L505

- “The `find` query uses the `loopback__model__name` as part of the query, sorted and limited to one item”
From the description, seems it's loopback api `findOne`, defined in https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L2140, NOT `findById`.

**Comment by b-admike** [comment]
@ritch thoughts on @jannyHou's comments? Is this still an issue?

**Comment by jannyHou** [comment]
Thank you @b-admike we recently realized `Cloudant.prototype.find(alias findById)` is not called by any dao.js functions yet. Which means the connector method is a optimized one while juggler function doesn't call it, but calls `Cloudant.prototype.all` instead.

Plan to support optimized `findById` in juggler:
- In dao.js `DataAccessObject.findById`,
  ```
    if (connector has findById function) {
    connector.findById(id, cb)
    } else {
      this.findOne(query)
    }
  ```

@ssh24 created a PR try to implement it but it fails lots connectors. We need to well plan how to support it.

**Comment by jannyHou** [comment]
@ssh24 PR: https://github.com/strongloop/loopback-datasource-juggler/pull/1459

**Comment by kjdelisle** [comment]
Closing as this is not a Cloudant issue; I've moved the related juggler PR into Review on our board.
