### ISSUE TITLE
Fix update/updateOrCreate in cloudant.js 

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-cloudant#35]
Use `updateAttributes` function to `update` a model instance and use `update` function in call for `updateOrCreate`. 

Currently, `update` performs a destructive update. With this change `update` function should be partial update.

**Comment by djorg83** [comment]
Possibly related to #110

**Comment by jannyHou** [comment]
@djorg83 thanks for catching the error in #110 , this is not the same one.
cloudant only support full replace of document, but not partial update.
This issue will implement an update method which does partial update.

**Comment by jannyHou** [comment]
Some possible solutions:

- Keep it same as `replaceOrCreate`, and warn users there is not partial update.
- (Tricky) We implement a way to merge data from document and updated data, then call `_insert` , which will do replace
- Throw error/warning in this method to explicitly tell user they need to define their own method if they do want to partial update.

**Comment by cwadding** [comment]
@jannyHou one solution for a partial update are to use update handlers https://cloud.ibm.com/docs/services/Cloudant/api?topic=cloudant-design-documents#update-handlers
This would need to be enabled on the cloudant database but can make it so that the updates are not a destructive operation.
It might would be nice to be able to specify the desired update handler
