### ISSUE TITLE
updateAll function should return an object

### ISSUE THREAD

**Issue by jmereaux** [strongloop/loopback-connector-cloudant#37]
Hi,

According to this [link](https://github.com/strongloop/loopback/issues/1167), the updateAll function of the connector should now return an object like:

`{ count: <numberOfRecordsUpdated> }` 

Could you please make the change?
Thanks

**Comment by jannyHou** [comment]
Hi @jmereaux Thanks for reminding us of making changes consistently.

If I understand correctly, now [`Cloudant.prototype.updateAll`](https://github.com/strongloop/loopback-connector-cloudant/blob/master/lib/cloudant.js#L563) returns the whole result object instead of the count only.

I reproduced it on my local. Label it as a bug here.

**Comment by ssh24** [comment]
Issue fixed on PR https://github.com/strongloop/loopback-connector-cloudant/pull/145.

Also backported for 1.x https://github.com/strongloop/loopback-connector-cloudant/pull/146

1.x shall be released first, while the fix on 2.x will go out when 2.x is released in the upcoming weeks.
